// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVbWN35IQN-nzrNbtAjYxi2dwLacWbPCI',
    appId: '1:903509884558:web:e78a3537320037546413df',
    messagingSenderId: '903509884558',
    projectId: 'mathgiveup-bc47a',
    authDomain: 'mathgiveup-bc47a.firebaseapp.com',
    storageBucket: 'mathgiveup-bc47a.appspot.com',
    measurementId: 'G-D7MWM38J1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnbbXHpaPO-JSo0Q3iU9a0bd0YYCrxNkE',
    appId: '1:903509884558:android:c1d9a31959de8fab6413df',
    messagingSenderId: '903509884558',
    projectId: 'mathgiveup-bc47a',
    storageBucket: 'mathgiveup-bc47a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbuaJrQ7z87KlKGQRQ-i4IzgW4BU6ZCfQ',
    appId: '1:903509884558:ios:41139d965f0883ba6413df',
    messagingSenderId: '903509884558',
    projectId: 'mathgiveup-bc47a',
    storageBucket: 'mathgiveup-bc47a.appspot.com',
    iosClientId: '903509884558-46l97r2ilosmd546c1dsfququ0nu1nua.apps.googleusercontent.com',
    iosBundleId: 'com.example.mathgame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbuaJrQ7z87KlKGQRQ-i4IzgW4BU6ZCfQ',
    appId: '1:903509884558:ios:41139d965f0883ba6413df',
    messagingSenderId: '903509884558',
    projectId: 'mathgiveup-bc47a',
    storageBucket: 'mathgiveup-bc47a.appspot.com',
    iosClientId: '903509884558-46l97r2ilosmd546c1dsfququ0nu1nua.apps.googleusercontent.com',
    iosBundleId: 'com.example.mathgame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVbWN35IQN-nzrNbtAjYxi2dwLacWbPCI',
    appId: '1:903509884558:web:acca5627504affe86413df',
    messagingSenderId: '903509884558',
    projectId: 'mathgiveup-bc47a',
    authDomain: 'mathgiveup-bc47a.firebaseapp.com',
    storageBucket: 'mathgiveup-bc47a.appspot.com',
    measurementId: 'G-Z6DJTHZVVX',
  );
}
